### ISSUE TITLE
Ntuple structure improvements - add objects

### ISSUE THREAD

**Issue by MDallOsso** [cms-hh-pd/alp_analysis#20]
I started to use the framework for trigger eff studies and I think it will be extremely useful if the format of alp_ ntuple can be equal to the one of alpha (our). 
A typical workflow is now:
- run on alpha ntuples with default script.
- then, after looking at output, need to change some event cuts
- have to re-run the modified script on alpha ntuples. 
  However, the last step has to be done on all events even if the different cut does not affect the baseline trigger.
  The best is to be able to run alp_   on alp ntuples too, without huge changes in the script.

To do so, we need to implement variables for other objects (muons, met,..).
A possibility is to implement all objects by default and to decide to save them in ntuples at script level.
i.e.  parse option in EventWriterOperator().
Or, we define which objects to use at the beginning of the script (maybe less computing time?).

Martino

**Comment by pablodecm** [comment]
Yes, I agree that the best would be to have the same format.

A combination of both approaches you mentioned would be the best, because loading more stuff from disk cause slower processing.  Nevertheless, I would prioritize being able to run on both over running time improvements.

**Comment by pablodecm** [comment]
I think can be closed
