### ISSUE TITLE
Dir format in the output file

### ISSUE THREAD

**Issue by MDallOsso** [cms-hh-pd/alp_analysis#3]
The name of directory in the output file is really annoying if it has to be read 'outside' alp or even via bash.
I understand that it is useful to track the cut sequence but we can maybe think about a more effective way to do that.

My proposal is to:
- encode the various steps description (e.g. 'trg_4jets30-2p5_csv0p800_...)
- write only histograms inside the folders
- write the tree always outside the folder with convention that it is filled always in the last selection step

Martino

**Comment by pablodecm** [comment]
Your proposal is good, I really think having so many nested folders is annoying. 

Any idea on how to encode the steps in a cool way as you suggest automatically? Regarding the WriterOperator for TTrees we could have an argument in the selector that it make it by default outside any folde but I suggest keeping the default option inside a single folder as you suggest for the histograms.
