### ISSUE TITLE
weird issue with Process()

### ISSUE THREAD

**Issue by MDallOsso** [cms-hh-pd/alp_analysis#42]
I got a weird issue...
I moved to CMSSW_8_0_25 (release used for new alpha ntuples) and I run on new ntuples.
On signal I do not have issue while on data I get this message:
```
 ### processing BTagCSVRun2016B-23Sep2016-v3
gen numEv 75566176.0
empty files 0
max numEv 100000
Traceback (most recent call last):
  File "scripts/BaselineSelector.py", line 207, in <module>
    tchain.Process(selector, procOpt, nev)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  Long64_t TChain::Process(const char* filename, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    could not convert argument 1 (expected string or Unicode object, ComposableSelector<alp::Event> found)
  Long64_t TChain::Process(TSelector* selector, const char* option = "", Long64_t nentries = kMaxEntries, Long64_t firstentry = 0) =>
    vector::_M_range_check: __n (which is 0) >= this->size() (which is 0) (C++ exception of type out_of_range)
-bash-4.1$ 
```

My guess is that it is related to Long64_T (nevents) but I am puzzled because it fails even if I set max nevt = 100000

**Comment by MDallOsso** [comment]
I run branch 'moriond17_dev' from the 'old' CMSSW_8_0_12 area and I got same issue with new data ntuples.
I run branch 'master'  and I got same issue with new data ntuples.

**Comment by pablodecm** [comment]
the Process method has to be debugged, it is that some std::vector goes out of range but with just that information is not enough for me to tell, could be even in some of the operators. Indeed, the actual error is trying to access the first element of an empty vector. The nevt should not affect.

**Comment by MDallOsso** [comment]
you are right, I got confused.
I found the origin of it in:
https://github.com/cms-hh-pd/alp_analysis/blob/master/interface/EventWriterOperator.h#L116

solved.
